name: Discord events

on:
  issue_comment: 
  issues: 
  label: 
  
jobs:
  test:
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm install discord.js
          npm install octokit
          echo $GITHUB_CONTEXT
          echo "$GITHUB_CONTEXT" > ./payload.json
          node index.js
