name: Discord events

on:
  issue_comment: 
  issues: 
  label: 
  
jobs:
  test:
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          DISCORD_ADMIN_USERNAME: ${{ vars.DISCORD_ADMIN_USERNAME }}
          DISCORD_SERVER_ID: ${{ vars.DISCORD_SERVER_ID }}
          DISCORD_INPUT_FORUM_CHANNEL_ID: ${{ vars.DISCORD_INPUT_FORUM_CHANNEL_ID }}
        run: |
          touch .env
          echo "DISCORD_TOKEN=$DISCORD_TOKEN" >> .env
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> .env
          echo "DISCORD_ADMIN_USERNAME=$DISCORD_ADMIN_USERNAME" >> .env
          echo "DISCORD_SERVER_ID=$DISCORD_SERVER_ID" >> .env
          echo "DISCORD_INPUT_FORUM_CHANNEL_ID=$DISCORD_INPUT_FORUM_CHANNEL_ID" >> .env
          
          npm install discord.js
          npm install octokit
          echo "$GITHUB_CONTEXT" > ./payload.json
          node index.js -e ""
