name: Discord events

on:
  issue_comment: 
  issues: 
  label: 
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 12
      - run: echo ${{ github.event}}
